"""Add status to latex_ai_runs

Revision ID: 2ba62a0adb59
Revises: c3f1a6b9d2e4
Create Date: 2026-01-30 00:49:38.793697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba62a0adb59'
down_revision: Union[str, None] = 'c3f1a6b9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_index('ix_comments_discussion_id', table_name='comments')
    op.drop_index('ix_comments_parent_id', table_name='comments')
    op.drop_index('ix_discussions_author_id', table_name='discussions')
    op.drop_index('ix_discussions_library_item_id', table_name='discussions')
    op.drop_index('ix_discussions_problem_id', table_name='discussions')
    op.add_column('latex_ai_runs', sa.Column('status', sa.String(length=32), server_default='pending', nullable=False))
    op.drop_constraint('teams_slug_key', 'teams', type_='unique')
    op.drop_index('ix_teams_slug', table_name='teams')
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.create_index('ix_teams_slug', 'teams', ['slug'], unique=False)
    op.create_unique_constraint('teams_slug_key', 'teams', ['slug'])
    op.drop_column('latex_ai_runs', 'status')
    op.create_index('ix_discussions_problem_id', 'discussions', ['problem_id'], unique=False)
    op.create_index('ix_discussions_library_item_id', 'discussions', ['library_item_id'], unique=False)
    op.create_index('ix_discussions_author_id', 'discussions', ['author_id'], unique=False)
    op.create_index('ix_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_discussion_id', 'comments', ['discussion_id'], unique=False)
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    # ### end Alembic commands ###
