"""add_formula_and_canvas_status

Revision ID: 8ad652486ed5
Revises: 0780fc9f9636
Create Date: 2026-01-25 01:45:35.843099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ad652486ed5'
down_revision: Union[str, None] = '0780fc9f9636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    canvas_status = postgresql.ENUM('DRAFT', 'VERIFIED', 'REVIEWING', name='canvas_status')
    canvas_status.create(op.get_bind(), checkfirst=True)
    
    # Add column as nullable first, then set default for existing rows
    op.add_column('canvases', sa.Column('status', canvas_status, nullable=True))
    op.execute("UPDATE canvases SET status = 'DRAFT'")
    op.alter_column('canvases', 'status', nullable=False)
    
    op.add_column('library_items', sa.Column('formula', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_items', 'formula')
    op.drop_column('canvases', 'status')
    op.execute('DROP TYPE IF EXISTS canvas_status')
    # ### end Alembic commands ###
