"""add_folder_to_canvas

Revision ID: dfe7e590422d
Revises: 8ad652486ed5
Create Date: 2026-01-25 02:33:51.367840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe7e590422d'
down_revision: Union[str, None] = '8ad652486ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Fix: Add column nullable, update default, then set not null
    op.add_column('canvases', sa.Column('folder', sa.String(length=512), nullable=True))
    op.execute("UPDATE canvases SET folder = '/'")
    op.alter_column('canvases', 'folder', nullable=False)

    op.alter_column('canvases', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'VERIFIED', 'REVIEWING', name='canvas_status'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::canvas_status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvases', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'VERIFIED', 'REVIEWING', name='canvas_status'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::canvas_status"))
    op.drop_column('canvases', 'folder')
    # ### end Alembic commands ###
