"""add_canvas_ai_models

Revision ID: ea7c51c4ad89
Revises: 368e12ac7812
Create Date: 2026-02-02 12:42:47.790297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea7c51c4ad89'
down_revision: Union[str, None] = '368e12ac7812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('redis_job_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canvas_ai_runs_problem_created', 'canvas_ai_runs', ['problem_id', 'created_at'], unique=False)
    op.create_index('ix_canvas_ai_runs_problem_status', 'canvas_ai_runs', ['problem_id', 'status'], unique=False)
    op.create_index('ix_canvas_ai_runs_status', 'canvas_ai_runs', ['status'], unique=False)
    op.create_table('canvas_ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['canvas_ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canvas_ai_messages_problem_created', 'canvas_ai_messages', ['problem_id', 'created_at'], unique=False)
    op.create_index('ix_canvas_ai_messages_run', 'canvas_ai_messages', ['run_id'], unique=False)
    op.create_table('canvas_ai_node_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('temp_node_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['canvas_ai_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canvas_ai_node_states_node', 'canvas_ai_node_states', ['node_id'], unique=False)
    op.create_index('ix_canvas_ai_node_states_run', 'canvas_ai_node_states', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canvas_ai_node_states_run', table_name='canvas_ai_node_states')
    op.drop_index('ix_canvas_ai_node_states_node', table_name='canvas_ai_node_states')
    op.drop_table('canvas_ai_node_states')
    op.drop_index('ix_canvas_ai_messages_run', table_name='canvas_ai_messages')
    op.drop_index('ix_canvas_ai_messages_problem_created', table_name='canvas_ai_messages')
    op.drop_table('canvas_ai_messages')
    op.drop_index('ix_canvas_ai_runs_status', table_name='canvas_ai_runs')
    op.drop_index('ix_canvas_ai_runs_problem_status', table_name='canvas_ai_runs')
    op.drop_index('ix_canvas_ai_runs_problem_created', table_name='canvas_ai_runs')
    op.drop_table('canvas_ai_runs')
    # ### end Alembic commands ###
